type Form {
    id: ID!
    title: String!
    fields: [Field!]!
}

interface Field {
    id: ID!
    title: String!
    order: Int!
}

type SingleChoiceField implements Field {
    options: [Option!]!
}

type TextField implements Field {
    dummy: Int
}

type Response {
    id: ID!
    form: Form!
    entries: [Entry!]!
}

interface Entry {
    id: ID!
    field: Field!
}

type SingleChoiceEntry implements Entry {
    option: Option!
}

type TextEntry implements Entry {
    text: String!
}

type Option {
    id: ID!
    title: String!
    order: Int!
}