type Form {
    id: ID!
    title: String!
    fields: [Field!]!
    responses: [Response!]
}

type Field {
    id: ID!
    order: Int!
    type: FieldType!
    entries: [Entry!]
    title: String!
    options: [FieldOption!]
    count: Int
}

enum FieldType {
    Date
    Rating
    SingleChoice
    Text
}

type FieldOption {
    id: ID!
    order: Int!
    title: String!
}

type Response {
    id: ID!
    form: Form! @hasInverse(field: responses)
    entries: [Entry!]! @hasInverse(field: response)
}

type Entry {
    id: ID!
    response: Response!
    field: Field! @hasInverse(field: entries)

    date: DateTime
    rating: Int
    singleChoice: FieldOption
    text: String
}
